version: '3.9'

services:
  next-app-layout:
    container_name: next-app-layout_container
    tty: true
    volumes:
      - .:/app
    command: >
      sh -c "yarn install && yarn dev"
    build:
      context: .
      dockerfile: next.Dockerfile
    image: next-app-layout_image:2.0
    ports:
      - "4000:4000"
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: none
    stdin_open: true