version: '3.9'

services:
  next-app-layout:
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: next.Dockerfile
    command: >
      sh -c "yarn dev"
    ports:
      - "4000:4000"